services:
  client:
    image: letters
    container_name: letters
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '${CLIENT_PORT:-3000}:${CLIENT_PORT:-3000}'

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - .env
    # ports:
    #   - '${DB_PORT:-3306}:${DB_PORT:-3306}'
    volumes:
      - ./db/words-russian-nouns.sql:/docker-entrypoint-initdb.d/words-russian-nouns.sql:ro
