services:
  web:
    image: letters
    container_name: server
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_PORT: ${MARIADB_PORT}
      SERVER_PORT: ${SERVER_PORT}
      STATIC_DIR_PATH: ${STATIC_DIR_PATH}


  db:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "${MARIADB_PORT}:${MARIADB_PORT}"
    volumes:
      - ./db/words-russian-nouns.sql:/docker-entrypoint-initdb.d/words-russian-nouns.sql:ro
